### ISSUE TITLE
"Failed to apply runtime IOS patches"

### ISSUE THREAD

**Issue by therealkiddude** [DarkMatterCore/xyzzy-mod#8]
![image_2024-08-13_191425634](https://github.com/user-attachments/assets/2973a875-e6e1-48da-9c00-6089a7af6cb5)

**Comment by DarkMatterCore** [comment]
Please provide more details about your setup.

**Comment by therealkiddude** [comment]
I am running the homebrew software on the Dolphin Emulator, my virtual SD
card is 1 gigabyte, I did import a real Wii NAND. The software said it
failed to apply runtime IOS patches and the software asked me to exit.

**Comment by DarkMatterCore** [comment]
This application was designed to run on real hardware. Most of the keys are actually read from hardware components such as OTP and SEEPROM chips by performing low level register operations.

I'm not sure why you'd even want to dump keys from an open source emulator. If you're running xyzzy under Dolphin because someone else told you to do so, they've misled you.

**Comment by DarkMatterCore** [comment]
By the way, if you've got a full, raw NAND dump from a real Wii, odds are you also have a `keys.bin` file, which usually holds raw copies of the OTP and SEEPROM contents. You can extract individual keys from it as needed.

**Comment by therealkiddude** [comment]
And how am I supposed to do that? I'm gonna use the individual keys for
wad2bin
